name: RELEASE

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  release:
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node_version: [14.x]
        include:
          - os: windows-latest
            TARGET_PLATFORMS: win32

          - os: macos-latest
            TARGET_PLATFORMS: darwin

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Package Electron
        run: |
          npm i
          npm run rebuild-native
          npm run pack

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: true
          files: |
            LICENSE
            out/*.dmg
            out/*.exe
